spring:
  cloud:
    config:
      enabled: false

server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5_SIMPLY
      - WEB
      - WEBEMBEDDED
      - ANDROID_VR
      - TV
    remoteCipher:
      enabled: true
      url: "https://cipher.kikkia.dev/"

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      snapshot: false
  pluginsDir: "./plugins"
  defaultPluginRepository: "https://maven.lavalink.dev/releases"

  server:
    password: ${LAVALINK_SERVER_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
