server:
  port: 2333

lavalink:
  server:
    password: ${LAVALINK_SERVER_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - TVHTML5_SIMPLY
      - WEB
      - WEBEMBEDDED
      - ANDROID_VR
      - TV
    remoteCipher:
      enabled: true
      url: "https://cipher.kikkia.dev/"

pluginsDir: "./plugins"
